### ISSUE TITLE
Searches should default to songs only

### ISSUE THREAD

**Issue by radamant** [radamant/robut-rdio#8]
```
@dj find radio head
```

should find only songs that match 'radio head'

```
@dj find album stop making sense
```

should find albums matching 'stop making sense'

_bonus:_

```
@dj find songs by herbie hancock
@dj find albums by herbie hancock
```

**Comment by davidmfoley** [comment]
++

**Comment by burtlo** [comment]
Searches are now by default to **track**.

I added support for **album** and **artist**.

**Comment by radamant** [comment]
F(YER)I you can close issues with a commit message. Even in merge commits.
