### ISSUE TITLE
Include icons in gemspec

### ISSUE THREAD

**Issue by radamant** [radamant/robut-rdio#9]

**Comment by burtlo** [comment]
I changed the `gemspec` to use the results of `git ls-files` instead of listing them all out manually as compiled from gemspec.

**Comment by burtlo** [comment]
I don't think jeweler does all that much for us, so I would rather remove it.

**Comment by radamant** [comment]
As discussed IRL: seems like `git ls-files` conceals the actual file dependencies.  Will dicsuss more RE removing jeweler etc.

**Comment by burtlo** [comment]
The next gemspec creation from Jeweler will undo this which is great.
